<?php

$banner_model = $this->getBanner();
// $id=$banner_model->getBanner_Id();
// echo $id;
 ?><html>
<html>
<head>
    <title>Admin Banner</title>
</head>
<style>
     /* body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: pink; 
        } */

     form {
            width: 50%;
            text-align: center;
           
        }

    
        label {
            color:blue;
            display: inline-block;
            width: 150px;
            margin-right: 10px;
            text-align: left;
        }
        input, select {
            width: 200px;
        }
        #but{
            width: 15px;
            margin-left: 35px;
            
        }



</style>
<body>
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl("admin/banner/save") ?>" >
    <!-- <php print_r($this) ?> -->
    <h1 style= "color:blue; font-size:200%;">Admin banner Form</h1>

    <label>banner Id:</label>
                <input type="text" name="banner[banner_id]" value="<?php echo $banner_model->getBanner_Id()?>"><br><br>
       
       
                
    <label>Title:</label>
                <input type="text" name="banner[title]" value="<?php echo $banner_model->getTitle()?>"><br><br>
               
     <label>Banner Image:</label><!--//accept=".jpg,.jpeg,.png" class="box" -->
     <img src="<?php echo Mage::getBaseUrl().'media/banner/'.$banner_model->getBanner_Image(); ?>" alt="Banner Image" style="width: 50px; height: auto;"></td>
                  <input type="file" name="banner[banner_image]" value="<?php echo $banner_model->getBanner_Image(); ?>"/><br><br>

                  <!-- <php
                    // Check if the banner_model has an existing image path
                    $existingImagePath = $banner_model->getBanner_Image();
                    if (!empty($existingImagePath)) {
                        echo '<img src="' . Mage::getBaseUrl().'media/banner/' . $existingImagePath . '" alt="Current Banner Image" style="max-width: 200px; max-height: 200px;"><br>';
                        echo '<label>Current Image Path:</label>' . $existingImagePath . '<br>';
                    }
                    ?> -->


    <label>Status:</label>
                <select name="banner[status]" >
                    <option value='0'>Enabled</option>
                    <option value='1'>Disabled</option>
            <!-- <option value="1">Disabled</option> -->
        </select><br><br>

    <label>Show On:</label>
                <input type="text" name="banner[show_on]" placeholder="show_on" value="<?php echo $banner_model->getShow_On()?>"><br><br>
   
                    
                    
                
        
                <input type="submit" name="submit" value="submit"style="color:blue; font-size:150%;border-radius:80px;">
               <!-- <a href="functions.php?edit=?php echo $no;?" >edit</a>-->

                
            </form>
</body>
</html> 