<?php

$banner_model = $this->getBanner();
// $id=$banner_model->getBanner_Id();
// echo $id;
 ?>
 <!-- <html>
<html>
<head>
    <title>Admin Banner</title>
</head> -->
<!-- <style>
     /* body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: pink; 
        } */

     form {
            width: 50%;
            text-align: center;
           
        }

    
        label {
            color:blue;
            display: inline-block;
            width: 150px;
            margin-right: 10px;
            text-align: left;
        }
        input, select {
            width: 200px;
        }
        #but{
            width: 15px;
            margin-left: 35px;
            
        }



</style> -->
<body>
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl("admin/banner/save") ?>" class="col-md-6 mx-auto">
    <input type="hidden" name="banner[banner_id]" value="<?php echo $banner_model->getBanner_Id()?>">

    <div class="form-group">
       <center> <h1 style="color:blue; font-size:200%;">Admin banner Form</h1></center>
    </div>

    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" name="banner[title]" class="form-control" value="<?php echo $banner_model->getTitle()?>">
    </div>

    <div class="form-group">
        <label for="banner_image">Banner Image:</label>
        <img src="<?php echo Mage::getBaseUrl().'media/banner/'.$banner_model->getBanner_Image(); ?>" class="form-control-file" alt="Banner Image" style="width: 200px; height: 150px; padding:10px;">
        <input type="file" name="banner[banner_image]" class="form-control-file">
    </div>

    <div class="form-group">
        <label for="status">Status:</label>
        <select name="banner[status]" class="form-control">
            <option value='0'>Enabled</option>
            <option value='1'>Disabled</option>
        </select>
    </div>

    <div class="form-group">
        <label for="show_on">Show On:</label>
        <input type="text" name="banner[show_on]" class="form-control" placeholder="show_on" value="<?php echo $banner_model->getShow_On()?>">
    </div>

    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>

</body>
</html> 