<?php
$bannerCollection = Mage::getModel('banner/banner')->getCollection();
foreach ($bannerCollection->getData() as $product) {
    //echo Mage::getBaseUrl().'media/banner/'.$product->getBanner_Image(); 
}
?>

<div class="container">
    <h1 class="mt-4">Admin Banner Table</h1>
    <div class="table-responsive">
        <table class="table table-bordered mt-4">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Show On</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($bannerCollection->getData() as $product) { ?>
                    <tr>
                        <td><?php echo $product->getBanner_Id(); ?></td>
                        <td><?php echo $product->getTitle(); ?></td>
                        <td>
                            <img src="<?php echo Mage::getBaseUrl() . 'media/banner/' . $product->getBanner_Image(); ?>" alt="Banner Image" style="height:90px;width:120px;">
                        </td>
                        <td><?php echo $product->getStatus(); ?></td>
                        <td><?php echo $product->getShow_On(); ?></td>
                        <td>
                            <button class="btn btn-primary edit-button" style="color: white;">
                                <a href='<?php echo $this->getUrl('admin/banner/form') ?>?id=<?php echo $product->getBanner_Id() ?>' style="color: inherit;">Edit</a>
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-danger delete-button" style="color: white;">
                                <a href='<?php echo $this->getUrl('admin/banner/delete') ?>?id=<?php echo $product->getBanner_Id() ?>' style="color: inherit;">Delete</a>
                            </button>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
