<?php
$customerData = $this->getCustomerData(); //order_id,order number      //sales/order




?>
<div class="container" style="margin-top:20px;">
    <div class="table overflow-x-scroll">
        <table class="table table-striped">
            <tr>
                <th>Customer ID</th>
                <th>Customer Email </th>
                <th>Password</th>
                <th>First Name</th>
                <th>Last Name</th>
                
            </tr>

            <?php foreach ($customerData as $customer) { ?>
                
                    <tr>
                        <td>
                            <?php echo $customer->getCustomer_id(); ?>
                        </td>
                        <td>
                            <?php echo $customer->getCustomerEmail(); ?>
                        </td>
                        <td>
                            <?php echo $customer->getPassword(); ?>
                        </td>
                        <td>
                            <?php echo $customer->getFirstName(); ?>
                        </td>
                        <td>
                            <?php echo $customer->getLastName(); ?>
                        </td>

                        
                        

                    </tr>
                </form>
            <?php } ?>
        </table>
    </div>
</div>