
<body>

<div class="container">
        <div class="card mt-5 mx-auto" style="max-width: 400px;"> <!-- Use Bootstrap card class -->
            <div class="card-body">
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" action="<?php echo $this->getUrl("admin/account/login") ?>">
    <!-- <php print_r($this) ?> -->
    <center><h1 class="card-title" style="color:blue; font-size:200%;">Admin Login</h1></center>

                
    <div class="form-group">
                        <label for="user">Admin Username:</label>
                <input type="text" name="admin[username]" placeholder="enter username" class="form-control">
    </div>

    <div class="form-group">
            <label for="password">Password:</label>
                <input type="text" name="admin[password]" placeholder="enter password" class="form-control"><br><br>
    </div>
               
         
    <div class="form-group">
                <input type="submit" name="submit" value="submit" class="btn btn-primary">
               <!-- <a href="functions.php?edit=?php echo $no;?" >edit</a>-->
    </div>
             

                
            </form>
</body>
</html> 