
<?php

$error = "";
if(isset($_GET['id'])){
     $no = $_GET['id'];     
}else{
 $error= "select category";
}

// $test=array('where'=>'');
// var_dump(isset($test['where']));

// die;
$categoryCollection=Mage::getModel('category/category')->load($no);
                    
$productCollection = Mage::getModel('catalog/product')->getCollection()
    ->addFieldToFilter('category_id',$no);
    $productCollection->groupBy('total_cost');
    //->addFieldToFilter('total_cost',['gt'=> 5]);
    // if (count($productCollection->getData()) == 0) {
    //     $error = "not data found";
    // }

    

    // foreach ($productCollection->getData() as $product) {
    //     var_dump($product);

    //   var_dump($product->getsku());
?>

<section>
  <div class="text-center container py-5">
    <h4 class="mt-4 mb-5"><strong><?php echo $categoryCollection->getCategory_name(); ?></strong></h4>

    <div class="row">
    <?php foreach($productCollection->getData() as $product) {  
       ?>

      <div class="col-lg-4 col-md-12 mb-4">
        <div class="card">
          <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
            data-mdb-ripple-color="light">
            <img src="<?php echo Mage::getBaseUrl().'media/product/'.$product->getImage_Link(); ?>" style="height:200px;width:150px;"
              class="w-100" />
            <a href="#!">
              <!-- <div class="mask">
                <div class="d-flex justify-content-start align-items-end h-100">
                  <h5><span class="badge bg-primary ms-2">New</span></h5>
                </div>
              </div> -->
              <div class="hover-overlay">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
              </div>
            </a>
          </div>
          <div class="card-body">
            <a href="<?php echo $this->getUrl('catalog/product/view') ?>?id=<?php echo $product->getId() ?>" class="text-reset">
              <h5 class="card-title mb-3"><?php echo $product->getname(); ?></h5>
            </a>
            <h6 class="mb-3"><?php echo $product->getDescription(); ?></h6>
            <h6 class="mb-3"><?php echo $product->getSize(); ?></h6>
            <h6 class="mb-3"><?php echo $product->getTotal_Cost(); ?></h6>

            <a href="<?php echo $this->getUrl('catalog/product/view') ?>?id=<?php echo $product->getId() ?>" class="btn btn-primary btn-sm">Add To Cart</a>

          </div>
        </div>
      </div>
      <?php } ?>

    </div>


  </div>
</section>




