<?php

$productCollection = Mage::getModel('catalog/product')->getCollection();
    //->addFieldToFilter('name','ty');

    // foreach ($productCollection->getData() as $product) {
    //     var_dump($product);
    // }
    //   var_dump($product->getsku());
?>
<body>
    <div class="container mt-8">
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th>Id</th>
                                <th>SKU</th>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Description</th>
                                <th>Link</th>
                                <th>Price</th>
                                <th>Mfr Cost</th>
                                <th>Shipping Cost</th>
                                <th>Total Cost</th>
                                <th>Margin Percentage</th>
                                <th>Margin Price</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($productCollection->getData() as $product) { ?>
                                <tr>
                                    <td><?php echo $product->getId(); ?></td>
                                    <td><?php echo $product->getSku(); ?></td>
                                    <td><?php echo $product->getName(); ?></td>
                                    <td><img src="<?php echo Mage::getBaseUrl().'media/product/'. $product->getImage_Link(); ?>" style="height:40px;width:40px;" alt="product"></td>
                                    <td><?php echo $product->getColor(); ?></td>
                                    <td><?php echo $product->getSize(); ?></td>
                                    <td><?php echo $product->getDescription(); ?></td>
                                    <td><?php echo $product->getLink(); ?></td>
                                    <td><?php echo $product->getPrice(); ?></td>
                                    <td><?php echo $product->getMfr_Cost(); ?></td>
                                    <td><?php echo $product->getShipping_Cost(); ?></td>
                                    <td><?php echo $product->getTotal_Cost(); ?></td>
                                    <td><?php echo $product->getMargin_Percentage(); ?></td>
                                    <td><?php echo $product->getMin_Price(); ?></td>
                                    <td>
                                        <a href="<?php echo $this->getUrl('admin/catalog_product/form') ?>?id=<?php echo $product->getId() ?>" class="btn btn-primary btn-sm">Edit</a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->getUrl('admin/catalog_product/delete') ?>?id=<?php echo $product->getId() ?>" class="btn btn-danger btn-sm">Delete</a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

 </body>