<!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" /> -->
<?php
$order=$this->orderDetails();
// print_r($order);
$address=$this->customerAddress();
// print_r($address);
$customer=$this->customerDetails();
//print_r($customer);
$items=$this->itemsDetails();
$product=$this->productDetails();
// print_r($product);
$payment=$this->paymentDetails();
// print_r($payment);
$shipping=$this->shippingDetails();
// print_r($shipping);
$history=$this->historyDetails();
// print_r($history);   




?>
<div class="page-content container">
    <div class="page-header text-blue-d2">
        <h1 class="page-title text-secondary-d1">
            Order-ID:
            <small class="page-info">
                <i class="fa fa-angle-double-right text-80"></i>
                 #111-222
            </small>
        </h1>

        <!-- <div class="page-tools">
            <div class="action-buttons">
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="Print">
                    <i class="mr-1 fa fa-print text-primary-m1 text-120 w-2"></i>
                    Print
                </a>
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="PDF">
                    <i class="mr-1 fa fa-file-pdf-o text-danger-m1 text-120 w-2"></i>
                    Export
                </a>
            </div>
        </div> -->
    </div>

    <div class="container px-0">
        <div class="row mt-4">
            <div class="col-12 col-lg-12">
                <!-- <div class="row">
                    <div class="col-12">
                        <div class="text-center text-150">
                            <i class="fa fa-book fa-2x text-success-m2 mr-1"></i>
                            <span class="text-default-d3">Bootdey.com</span>
                        </div>
                    </div>
                </div> -->
                <!-- .row -->

                <hr class="row brc-default-l1 mx-n1 mb-4" />

                <div class="row">
                    <div class="col-sm-6">
                        <div>
                            <span class="text-sm text-grey-m2 align-middle"><b class="text-600">Customer Details:</b></span>
                            <span class="text-600 text-110 text-blue align-middle"><?php echo $customer->getFirst_Name()." ".$customer->getLast_Name() ?></span>
                        </div>
                        <div class="text-grey-m2">
                        <?php foreach ($address as $addr) {  ?>
                            <div class="my-1">
                                Email: <?php echo $addr->getEmail() ?>
                            </div>
                            <div class="my-1">
                                Phone no: <?php echo $addr->getShipping_phone() ?>
                            </div>
                            <!-- <div class="my-1"><i class="fa fa-phone fa-flip-horizontal text-secondary"></i> <b class="text-600">111-111-111</b></div> -->
                        </div>
                    </div>
                    <!-- /.col -->

                    <div class="text-95 col-sm-6 align-self-start d-sm-flex justify-content-end">
                        <hr class="d-sm-none" />
                        <div class="text-grey-m2">
                            <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                            <b class="text-600">Shipping Address:</b>
                            </div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Shipping Address:</span><?php echo $addr->getShipping_address() ?></div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Shipping City:</span><?php echo $addr->getShipping_city() ?></div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Shipping Region:</span><?php echo $addr->getShipping_Region() ?></div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Shipping Country:</span><?php echo $addr->getShipping_country() ?></div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Shipping Postcode:</span><?php echo $addr->getShipping_post_code() ?></div>

                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Status:</span> <span class="badge badge-warning badge-pill px-25">ghthy</span></div>
                        </div>
                    </div>
                    <!-- /.col --><?php } ?>
                </div>

                <hr class="row brc-default-l1 mx-n1 mb-4" />
                <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                    <b class="text-600">Item Details</b>
                </div>
                <div class="mt-4">
                <div class="row text-600 text-white bgc-default-tp1 py-25">
                
                    <div class="col-3 col-sm-2">Name</div> 
                    <div class="col-3 col-sm-2">Image</div> 
                    <div class="col-3 col-sm-3">Description</div> 
                    <div class="col-1 col-sm-1">Price</div> 
                    <div class="col-1 col-sm-1">Qty</div> 
                    <div class="col-1 col-sm-1">total cost</div> 
                </div>

                <div class="text-95 text-secondary-d3">

                    <?php foreach ($items as $item) {  ?>
                        <div class="row mb-2 mb-sm-0 py-25">
                            <div class="col-3 col-sm-2"><?php echo $product->getName()?></div> 
                            <div class="col-3 col-sm-2"><img src="<?php echo Mage::getBaseUrl().'media/product/'.$product->getImage_Link(); ?>"
                                            class="img-fluid" alt="Generic placeholder image"></div> 
                            <div class="col-3 col-sm-3"><?php echo $product->getSku()?><br>
                                                        <?php echo $product->getColor()?><br>
                                                        <?php echo $product->getSize()?><br>
                                                        <?php echo $product->getDescription()?><br>
                                                        
                            </div> 
                            <div class="col-1 col-sm-1"><?php echo $item->getPrice()?></div> 
                            <div class="col-1 col-sm-1"><?php echo $item->getQty()?></div> 
                            <div class="col-1 col-sm-1"><?php echo $item->getRow_Total()?></div> 
                        </div>

                        <?php } ?>

                        

                        

                        
                    </div>
                    <hr class="row brc-default-l1 mx-n1 mb-4" />

                    <div class="row">
                    <div class="col-sm-6">
                        <div>
                            <span class="text-sm text-grey-m2 align-middle"><b class="text-600">Shipping Details:</b></span>
                        </div>
                        <div class="text-grey-m2">
                       
                            <div class="my-1">
                                Shipping Method: <?php echo $shipping->getShipping_method() ?>
                            </div>
                            
                            <!-- <div class="my-1"><i class="fa fa-phone fa-flip-horizontal text-secondary"></i> <b class="text-600">111-111-111</b></div> -->
                        </div>
                    </div>
                    <!-- /.col -->
                    <!-- <div class="col-12 col-sm-5 text-grey text-90 order-first order-sm-last"> -->

                    <div class="text-95 col-sm-4 align-self-start d-sm-flex justify-content-end">
                        <hr class="d-sm-none" />
                        <div class="text-grey-m2">
                            <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                            <b class="text-600">Payment Details:</b>
                            </div>
                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Payment Type:</span><?php echo $payment->getPayment_Method() ?></div>
                            <?php if($payment->getCard_number() != 0){ ?> 
                            <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Card Number:</span><?php echo $payment->getCard_number() ?></div>

                            <?php } ?>
                        </div>
                    </div>
                    
                </div>
                <hr class="row brc-default-l1 mx-n1 mb-4" />
                    <div class="row border-b-2 brc-default-l2"></div>

                    <!-- or use a table instead -->
                    <!--
            <div class="table-responsive">
                <table class="table table-striped table-borderless border-0 border-b-2 brc-default-l1">
                    <thead class="bg-none bgc-default-tp1">
                        <tr class="text-white">
                            <th class="opacity-2">#</th>
                            <th>Description</th>
                            <th>Qty</th>
                            <th>Unit Price</th>
                            <th width="140">Amount</th>
                        </tr>
                    </thead>

                    <tbody class="text-95 text-secondary-d3">
                        <tr></tr>
                        <tr>
                            <td>1</td>
                            <td>Domain registration</td>
                            <td>2</td>
                            <td class="text-95">$10</td>
                            <td class="text-secondary-d2">$20</td>
                        </tr> 
                    </tbody>
                </table>
            </div>
            -->

                    <div class="row mt-3">

                        <div class="col-12 col-sm-7 text-grey-d2 text-95 mt-2 mt-lg-0">
                        <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                            <b class="text-600">Status History:</b>
                        </div>
                        </div>

                        <div class="col-12 col-sm-5 text-grey text-90 order-first order-sm-last">

                        <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                            <b class="text-600">Order Summery:</b>
                        </div>
                            <div class="row my-2">
                                <div class="col-7 text-right">
                                    SubTotal
                                </div>
                                <div class="col-5">
                                    <span class="text-120 text-secondary-d1">$2,250</span>
                                </div>
                            </div>

                            <div class="row my-2">
                                <div class="col-7 text-right">
                                    Tax (10%)
                                </div>
                                <div class="col-5">
                                    <span class="text-110 text-secondary-d1">$225</span>
                                </div>
                            </div>

                            <div class="row my-2 align-items-center bgc-primary-l3 p-2">
                                <div class="col-7 text-right">
                                    Total Amount
                                </div>
                                <div class="col-5">
                                    <span class="text-150 text-success-d3 opacity-2">$2,475</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr />

                    <div>
                       <a href="#" class="btn btn-info btn-bold px-4 float-right mt-3 mt-lg-0">Pay Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>