<style>
    body {
    background-color: #f8f9fa;
  }
  .about-section {
    background-color: #ffffff;
    padding: 50px 0;
  }
  .about-section h2 {
    color: #2D9596;
    margin-bottom:20px ;
    
   
  }
  .about-section p {
    color: black;
    text-align: justify;
    font-size:medium;
  }
  .values-section {
    background-color: #f8f9fa;
    padding: 20px 0;
  }
  .value-item {
    text-align: center;
    margin-bottom: 30px;
  }
  .value-item i {
    font-size: 36px;
    margin-bottom: 20px;
    color: #2D9596;
  }
  .value-item h3 {
    color: #333;
  }
</style>
<section class="about-section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>About Us</h2>
        <p>Welcome to Aura, your ultimate destination for trendy and fashionable clothing. Founded in 2024, we have been serving fashion-forward individuals like you with our carefully curated collection of apparel.</p>
        <p>At Aura, we believe that fashion is not just about clothing; it's a way to express your personality and style. That's why we strive to bring you the latest trends and timeless classics that cater to every occasion and mood.</p>
        <p>Our commitment to quality is unwavering. Each piece in our collection is meticulously crafted using the finest materials and designed to provide both comfort and style. Whether you're dressing up for a special event or keeping it casual on a weekend, we've got you covered.</p>
        <p>But Aura is more than just a clothing store; it's a community of fashion enthusiasts who share a passion for self-expression through style. Join us on this journey as we continue to inspire and empower individuals to embrace their uniqueness.</p>
      </div>
      <div class="col-md-6">
        <img src="<?php echo Mage::getBaseUrl().'skin/images/aboutus.jpg'?>"  alt="About Us Image" height="500px">
      </div>
    </div>
  </div>
</section>

<!-- Values Section -->
<section class="values-section">
  <div style="text-align:center;color:#2D9596;" class="mb-5"><h2 >Our Values</h2></div>
  <div class="container">
    
    <div class="row">
      <div class="col-md-4">
        <div class="value-item">
          <i class="fas fa-heart"></i>
          <h3>Quality</h3>
          <p>We are committed to offering high-quality clothing made from the finest materials.</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="value-item">
          <i class="fas fa-users"></i>
          <h3>Community</h3>
          <p>We believe in building a supportive community where fashion enthusiasts can connect and share their passion.</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="value-item">
          <i class="fas fa-globe"></i>
          <h3>Diversity</h3>
          <p>We celebrate diversity and strive to offer clothing that caters to people of all backgrounds and identities.</p>
        </div>
      </div>
    </div>
  </div>
</section>
