<div class="container mt-3">
    <h2 style='color:#2D9596;text-align:center;margin:10px;'>Return Policy</h2>
        <p>
            We want you to be happy with your purchase. If you're not satisfied for any reason, you may return it within 30 days for a full refund or exchange.
        </p>
        <h3>Conditions</h3>
        <ul>
            <li>Item must be unused and in the same condition as received</li>
            <li>Must be returned with original packaging</li>
            <li>Some items may not be eligible for return (e.g.personalized items)</li>
        </ul>
        <h3>Refunds</h3>
        <p>
            Refunds will be processed within 5-7 business days after receiving the returned item.
        </p>
        <h3>Exchanges</h3>
        <p>
            If you need to exchange an item, please contact us at mailto:aura@gmail.com .
        </p>
        <h3>Shipping</h3>
        <p>
            You are responsible for return shipping costs unless the return is due to our error.
        </p>
        <h3>Contact Us</h3>
        <p>
            If you have any questions about our return policy, please contact us at mailto:aura@gmail.com .
        </p>
    </div>