<table>
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>id</th>
            <th>email</th>
            <th>first name</th>
            <th>last name</th>
            <th>billing address</th>
            <th>billing city</th>
            <th>billing region</th>
            <th>billing country</th>
            <th>billing phone</th>
            <th>shipping address</th>
            <th>shipping city</th>
            <th>shipping region</th>
            <th>shipping country</th>
            <th>shipping phone</th>
            <th>defult</th>
            
            

            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <!-- <php foreach($productCollection->getData() as $product) { ?>

            <tr>
            <td><php print_r($product->getid());?></td>
            <td><php print_r($product->getsku());?></td>
            <td><php print_r($product->getname());?></td>
            <td><php print_r($product->getcolor());?></td>
            <td><php print_r($product->getsize());?></td>
            <td><php print_r($product->getdescription());?></td>
            <td><php print_r($product->getimage_link());?></td>
            <td><php print_r($product->getlink()); ?></td>
            <td><php print_r($product->getprice());?></td>
            <td><php print_r($product->getmfr_cost());?></td>
            <td><php print_r($product->getshipping_cost());?></td>
            <td><php print_r($product->gettotal_cost());?></td>
            <td><php print_r($product->getmargin_percentage());?></td>
            <td><php print_r($product->getmin_price());?></td>


            <td><button class="edit-button"><a href='<php echo $this->getUrl('admin/catalog_product/form')?>?id=<?php echo $product->getId()?>'>Edit</a></button></td>
            <td><button class="delete-button"><a href='<php echo $this->getUrl('admin/catalog_product/delete')?>?id=<?php echo $product->getId()?>'>Delete</a></button></td>
            </tr>
            <php } ?> -->
    </table>
</div>

</table>

    

