<?php
$customerId = Mage::getSingleton('core/session')->get('logged_in_customer_id');
$productCollection = Mage::getModel('customer/customer')->getCollection()
    ->addFieldToFilter('customer_id', $customerId);
?>

<div class="container">
    <?php foreach ($productCollection->getData() as $info) ?>
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">Profile Information</h2>
                    <p><strong>Name:</strong> <?php echo $info->getfirst_Name() . ' ' . $info->getlastName(); ?></p>
                    <p><strong>Email:</strong> <?php echo $info->getcustomer_email(); ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">Billing Address</h2>
                    <p><strong>Address:</strong> <?php echo $info->getbilling_Address(); ?></p>
                    <p><strong>City:</strong> <?php echo $info->getbilling_City(); ?></p>
                    <p><strong>Region:</strong> <?php echo $info->getbilling_Region(); ?></p>
                    <p><strong>Country:</strong> <?php echo $info->getbilling_Country(); ?></p>
                    <p><strong>Phone:</strong> <?php echo $info->getbilling_Phone(); ?></p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">Shipping Address</h2>
                    <p><strong>Address:</strong> <?php echo $info->getshipping_Address(); ?></p>
                    <p><strong>City:</strong> <?php echo $info->getshipping_City(); ?></p>
                    <p><strong>Region:</strong> <?php echo $info->getshipping_Region(); ?></p>
                    <p><strong>Country:</strong> <?php echo $info->getshipping_Country(); ?></p>
                    <p><strong>Phone:</strong> <?php echo $info->getshipping_Phone(); ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="edit-delete-links">
                <button class="btn btn-primary edit-button"><a href="<?php echo $this->getUrl('customer/account/register') ?>?id=<?php echo $info->getcustomer_Id() ?>" style="color:white;">Edit</a></button>
            </div>
        </div>
    </div>
</div>
