<?php

// $customerData=$this->getCustomer();
// value="<?php echo $product_model->getcustomer_email()>"

// if(isset($_GET['id'])){
//      $no = $_GET['id'];     
// }
// else{
//     $no=0;
// }
$customer=$this->getCustomer();
// echo $id->getcustomer_Id();
 
// $customerCollection = Mage::getModel('customer/customer')->getCollection()
//     ->addFieldToFilter('customer_id', $id);
?>
<!-- value="<php echo $product_model->getid()?>" -->
<html>
<head>
    <title>Customer</title>
</head>
<style>
     /* body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: pink; 
        } */

     form {
            width: 50%;
            text-align: center;
           
        }

    
        label {
            color:blue;
            display: inline-block;
            width: 150px;
            margin-right: 10px;
            text-align: left;
        }
        input, select {
            width: 200px;
        }
        #but{
            width: 15px;
            margin-left: 35px;
            
        }



</style>
<body>
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" action="<?php echo $this->getUrl("customer/account/save") ?>">
    <!-- <php print_r($this) ?> -->
    <h1 style= "color:blue; font-size:200%;">Customer Registration</h1>

    
    <!-- <label>Customer Id:</label> -->
                <input type="hidden" name="data[customer_id]" value="<?php echo $customer->getcustomer_id()?>"><br><br>
       
        
                
    <label>Customer Email:</label>
                <input type="text" name="data[customer_email]" value="<?php echo $customer->getcustomer_email()?>"><br><br>
               
    <label>First Name:</label>
                <input type="text" name="data[first_name]" value="<?php echo $customer->getfirst_name()?>"><br><br>

    <label>Last Name:</label>
                <input type="text" name="data[last_name]" value="<?php echo $customer->getlast_name()?>"><br><br>
        
    <label>Bill Address:</label>
                <input type="textarea" name="data[billing_address]" placeholder="" value="<?php echo $customer->getbilling_Address()?>"><br><br>
        
    <label>Bill City:</label>
                <input type="text" name="data[billing_city]" placeholder="" value="<?php echo $customer->getbilling_City()?>"><br><br>

    <label>Bill Region:</label>
                <input type="text" name="data[billing_region]" placeholder="" value="<?php echo $customer->getbilling_Region()?>"><br><br>
      
    <label>Bill Country:</label>
                <input type="text" name="data[billing_country]" placeholder="" value="<?php echo $customer->getbilling_Country()?>"><br><br>
           
    <label>Billing Phone:</label>
                <input type="text" name="data[billing_phone]" placeholder="" value="<?php echo $customer->getbilling_Phone()?>"><br><br>
        
        
    <label>Shipping Address:</label>
                <input type="textarea" name="data[shipping_address]" placeholder="" value="<?php echo $customer->getshipping_Address()?>"><br><br>
        
    <label>Shipping City:</label>
                <input type="text" name="data[shipping_city]" placeholder="" value="<?php echo $customer->getshipping_City()?>"><br><br>

    <label>Shipping Region:</label>
                <input type="text" name="data[shipping_region]" placeholder="" value="<?php echo $customer->getshipping_Region()?>"><br><br>
      
    <label>Shipping Country:</label>
                <input type="text" name="data[shipping_country]" placeholder="" value="<?php echo $customer->getshipping_Country()?>"><br><br>
           
    <label>Shipping Phone:</label>
                <input type="text" name="data[shipping_phone]" placeholder="" value="<?php echo $customer->getshipping_Phone()?>"><br><br>

    <?php if(!isset($_GET['id'])) { ?>
    <label>Password:</label>
    <input type="text" name="data[password]" placeholder="" value="<?php echo $customer->getPassword()?>"><br><br>
    <?php } ?>            
           
    <label>Default:</label>
                <select name="data[dfault]" >
                    <option value='0'>Enabled</option>
                    <option value='1'>Disabled</option>
                    
                    
                    <!-- <option value="1">Disabled</option> -->
                </select><br><br>
        
                
        
                <input type="submit" name="submit" value="submit"style="color:blue; font-size:150%;border-radius:80px;">
               <!-- <a href="functions.php?edit=?php echo $no;?" >edit</a>-->

             

                
            </form>
            
</body>
</html> 