<?php

// $customerData=$this->getCustomer();
// value="<?php echo $product_model->getcustomer_email()>"

//  Mage::getSingleton('core/session')->get('customerId');

 //echo $this;
// $product_model = $this->getProduct();
//  $id=$customerData->getId();
// echo $id;
// $value=$product_model->getsku();
// echo $value;
 
?>
<!-- value="<php echo $product_model->getid()?>" -->
<html>
<head>
    <title>Customer</title>
</head>
<style>
     /* body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: pink; 
        } */

     form {
            width: 50%;
            text-align: center;
           
        }

    
        label {
            color:blue;
            display: inline-block;
            width: 150px;
            margin-right: 10px;
            text-align: left;
        }
        input, select {
            width: 200px;
        }
        #but{
            width: 15px;
            margin-left: 35px;
            
        }



</style>
<body>
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" action="<?php echo $this->getUrl("customer/account/save") ?>">
    <!-- <php print_r($this) ?> -->
    <h1 style= "color:blue; font-size:200%;">Product Form</h1>
<!-- 
    <label>Customer Id:</label>
                <input type="text" name="data[customer_id]" value="<php echo $product_model->getid()?>"><br><br>
       
        -->
                
    <label>Customer Email:</label>
                <input type="text" name="data[customer_email]" ><br><br>
               
    <label>First Name:</label>
                <input type="text" name="data[first_name]" placeholder="Enter color" ><br><br>

    <label>Last Name:</label>
                <input type="text" name="data[last_name]" placeholder="size" ><br><br>
        
    <label>Bill Address:</label>
                <input type="textarea" name="data[billing_address]" placeholder="description" ><br><br>
        
    <label>Bill City:</label>
                <input type="text" name="data[billing_city]" placeholder="image link" ><br><br>

    <label>Bill Region:</label>
                <input type="text" name="data[billing_region]" placeholder="image link" ><br><br>
      
    <label>Bill Country:</label>
                <input type="text" name="data[billing_country]" placeholder="image link"><br><br>
           
    <label>Billing Phone:</label>
                <input type="text" name="data[billing_phone]" placeholder="enter total cost" ><br><br>
        
        
    <label>Shipping Address:</label>
                <input type="textarea" name="data[shipping_address]" placeholder="description" ><br><br>
        
    <label>Shipping City:</label>
                <input type="text" name="data[shipping_city]" placeholder="image link"><br><br>

    <label>Shipping Region:</label>
                <input type="text" name="data[shipping_region]" placeholder="image link" ><br><br>
      
    <label>Shipping Country:</label>
                <input type="text" name="data[shipping_country]" placeholder="image link" ><br><br>
           
    <label>Shipping Phone:</label>
                <input type="text" name="data[shipping_phone]" placeholder="enter total cost" ><br><br>
                
    <label>Password:</label>
                <input type="text" name="data[password]" placeholder="enter password" ><br><br>
        
    <label>Default:</label>
                <select name="data[dfault]" >
                    <option value='0'>Enabled</option>
                    <option value='1'>Disabled</option>
                    
                    
                    <!-- <option value="1">Disabled</option> -->
                </select><br><br>
        
                
        
                <input type="submit" name="submit" value="submit"style="color:blue; font-size:150%;border-radius:80px;">
               <!-- <a href="functions.php?edit=?php echo $no;?" >edit</a>-->

             

                
            </form>
</body>
</html> 