<?php
$customerDetails=$this->customerOrder();
// print_r($customerDetails);
$orderCollection=$this->historyDetails();
// echo "<pre>";
// echo $orderCollection->getOrder_Id();
// $order = $orderCollection[0][0]; // Access the first element of the array and then the first object within it
// $order_id = $order->getOrder_Id(); // Assuming getOrder_Id() is the method to retrieve the order_id
// echo $order_id;



    //->addFieldToFilter('name','ty');

    // foreach ($productCollection->getData() as $product) {
    //     var_dump($product);
    // }
    //   var_dump($product->getsku());
?>
<body>
    <div class="container mt-8">
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th>Order Number</th>
                                <th>Grand Total</th>
                                <th>Status</th>
                                <th>create at</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        <?php foreach ($orderCollection as $index => $orderItemArray) {
                            foreach ($orderItemArray as $orderItem) {
                                $order = $orderItem;
                                ?>
                                <tr>
                                <td><?php echo $order->getOrder_Number();?></td>
                                    <td><?php echo $order->getGrand_Total(); ?></td>
                                    <td><?php echo $order->getStatus(); ?></td>
                                    <td><?php echo $order->getCreate_at(); ?></td>
                                    <td>
                                        <a href="<?php echo $this->getUrl('customer/account/order') ?>?id=<?php echo $order->getOrder_Id() ?>" class="btn btn-primary btn-sm">Edit</a>
                                    </td>
                                    
                                </tr>
                            <?php 
                            } 
                            }?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

 </body>