<?php
//  Mage::getSingleton('core/session')->get('customerId');

 //echo $this;
// $product_model = $this->getProduct();
// $id=$product_model->getId();
// echo $id;
// $value=$product_model->getsku();
// echo $value;
 
?>
<!-- value="<php echo $product_model->getid()?>" -->
<html>
<head>
    <title>Customer</title>
</head>
<style>
     /* body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: pink; 
        } */

     form {
            width: 50%;
            text-align: center;
           
        }

    
        label {
            color:blue;
            display: inline-block;
            width: 150px;
            margin-right: 10px;
            text-align: left;
        }
        input, select {
            width: 200px;
        }
        #but{
            width: 15px;
            margin-left: 35px;
            
        }



</style>
<body>
    <!-- <form method="POST" action="<php echo $this->getUrl("catalog/product/save") ?>"> -->
    <form method="POST" id ="login-form"action="<?php echo $this->getUrl("customer/account/login") ?>">
    <!-- <php print_r($this) ?> -->
    <h1 style= "color:blue; font-size:200%;">Product Form</h1>

                
    <label>Customer Email:</label>
                <input type="text" name="login[customer_email]" ><br><br>

    <label>Password:</label>
                <input type="text" name="login[password]" placeholder="enter password" ><br><br>
     
                <div class="col-md-6 mt-4">
		                <input type="button" onclick="loginAction(this)" value="Submit" class="btn btn-black btn-sm">
		              </div>
         
                <!-- <button name="submit" value="submit" onclick="loginAction($this)"> -->
        
                <!-- <input type="submit" name="submit" value="submit"style="color:blue; font-size:150%;border-radius:80px;"> -->
               <!-- <a href="functions.php?edit=?php echo $no;?" >edit</a>-->

             <div id="message"></div>

                
            </form>

            <script type="text/javascript">
                 function loginAction(btn){
                    var form=$($('#login-form')[0]);
                console.log(form.serialize());
                $.ajax({
                    url: form.action,
                    type:'POST',
                    // contentType: "application/json",
                    data: form.serialize()	
                }).done(function(response){
                    var output=JSON.parse(response);
                    alert(output.type)
                    $('#message')[0].innerHTML = output.message;
                    alert(output.message)
                    $( this ).addClass( "done" );
                    $( this ).addClass( "done" );
                });
                }
                </script>
</body>
</html> 