<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<?php echo $this->getUrl('admin/account/dashboard')?>">Admin Panel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $this->getUrl('admin/account/dashboard')?>">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $this->getUrl('admin/sales/list')?>">Orders</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProducts" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownProducts">
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/catalog_product/form')?>">Form</a>
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/catalog_product/list')?>">List</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCategories" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownCategories">
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/catalog_category/form')?>">Form</a>
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/catalog_category/list')?>">List</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBanners" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Banners
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownBanners">
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/banner/form')?>">Form</a>
            <a class="dropdown-item" href="<?php echo $this->getUrl('admin/banner/list')?>">List</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $this->getUrl('admin/customer/list')?>">Customers</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="<php echo $this->getUrl('admin/account/logout')?>">Logout</a>
        </li> -->
      </ul>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>