<?php


$bannerCollection = Mage::getModel('banner/banner')->getCollection();
$productCollection=Mage::getModel('catalog/product')->getCollection();
function category($id){
  $categoryCollection=Mage::getModel('category/category')->getCollection()->addFieldToFilter('category_id',$id);
  return $categoryCollection;
}
//print_r($bannerCollection->getData());

//  foreach($bannerCollection->getData() as $product) { 
//echo Mage::getBaseUrl().'media/banner/'.$product->getBanner_Image(); 

 ?>
 <div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="custCarousel" class="carousel slide" data-ride="carousel"  style="align:center;">
        <!-- slides -->
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="<?php echo Mage::getBaseUrl().'media/banner/'."main.jpg"; ?>" style="height:600px;width:1200px;"  alt="Banner">
          </div>

          <?php foreach($bannerCollection->getData() as $key =>$product) { ?>
          <div class="carousel-item">
            <img src="<?php echo Mage::getBaseUrl().'media/banner/'.$product->getBanner_Image(); ?>" style="height:600px;width:1200px;" alt="Banner">
          </div>

        <?php } ?>
        <!-- Left right -->
        <a class="carousel-control-prev" href="#custCarousel" data-slide="prev" >
          <span class="carousel-control-prev-icon" style="background-color: #7B1FA2;"></span>
        </a>
        <a class="carousel-control-next" href="#custCarousel" data-slide="next" >
          <span class="carousel-control-next-icon" style="background-color: #7B1FA2;"></span>
        </a>

        <!-- Thumbnails -->
       
      </div>
    </div>
  </div>
</div>

<hr class="row brc-default-l1 mx-n1 mb-4" />

<section style="background-color: #eee;">
  <div class="text-center container py-5">
    <h4 class="mt-4 mb-5"><strong>Products</strong></h4>

    <div class="row">
    <?php foreach($productCollection->getData() as $product) {  
      $cid=$product->getCategory_Id();
      $category=category($cid); ?>

      <div class="col-lg-4 col-md-12 mb-4">
        <div class="card">
          <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
            data-mdb-ripple-color="light">
            <img src="<?php echo Mage::getBaseUrl().'media/product/'.$product->getImage_Link(); ?>" style="height:150px;width:80px;"
              class="w-100" />
            <a href="#!">
              <!-- <div class="mask">
                <div class="d-flex justify-content-start align-items-end h-100">
                  <h5><span class="badge bg-primary ms-2">New</span></h5>
                </div>
              </div> -->
              <div class="hover-overlay">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
              </div>
            </a>
          </div>
          <div class="card-body">
            <a href="<?php echo $this->getUrl('catalog/product/view') ?>?id=<?php echo $product->getId() ?>" class="text-reset">
              <h5 class="card-title mb-3"><?php echo $product->getname(); ?></h5>
            </a>
            <?php foreach($category->getData() as $category) {?>
            <a href="<?php echo $this->getUrl('catalog/category/view') ?>?id=<?php echo $cid ?>" class="text-reset">
              <p><?php echo $category->getCategory_name(); ?></p>
            </a><?php } ?>
            <h6 class="mb-3"><?php echo $product->getTotal_Cost(); ?></h6>

            <a href="<?php echo $this->getUrl('catalog/product/view') ?>?id=<?php echo $product->getId() ?>" class="btn btn-primary btn-sm">Add To Cart</a>

          </div>
        </div>
      </div>
      <?php } ?>

    </div>


  </div>
</section>


