<!-- <h1>footer.phtml</h1> -->
<!-- <php echo get_class($this); ?> -->


<!-- Footer -->
<footer class="bg-primary text-center text-white" >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-facebook-f">
                <img src="<?php echo Mage::getBaseUrl() .'skin/images/facebook.png'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 
                
                </i>
            </a>

            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-2" href="#!" role="button">
                <!-- <i class="fab fa-twitter"></i> -->
                <img src="<?php echo Mage::getBaseUrl() .'skin/images/twitter.png'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 
                
            
            </a>

            <!-- Google -->
            <!-- <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-google"></i>
                <img src="<php echo Mage::getBaseUrl() .'skin/images/.png'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 
                
        
            </a> -->

            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <!-- <i class="fab fa-instagram"></i> -->
                <img src="<?php echo Mage::getBaseUrl() .'skin/images/insta.png'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 

        
            </a>

            <!-- Linkedin -->
            <!-- <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-linkedin-in"></i>
                <img src="<php echo Mage::getBaseUrl() .'skin/images/linked1.jpg'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 

        
            </a> -->

            <!-- Github -->
            <!-- <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-github"></i> 
                <img src="<php echo Mage::getBaseUrl() .'skin/images/github.png'?>" alt="Custom Image" style="width: 30px; height: 30px;"> 

        
            </a>-->
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2024 Copyright:
        <a class="text-white" href="#">.com</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
